server:
  port: 8089

spring:
  profiles:
    active: dev
  datasource:
    # MySQL
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.106:3306/demo-simple?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Tokyo&nullCatalogMeansCurrent=true
    username: root
    password: 123456

storage:
  path: C:/upload

mybatis-plus:
  mapper-locations: classpath:/mapper/*.xml
  typeAliasesPackage: io.hugang.demo.simple.entity
  global-config:
    db-config:
      id-type: AUTO
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    call-setters-on-nulls: true
    jdbc-type-for-null: 'null'
  configuration-properties:
    prefix:
    blobType: BLOB
    boolValue: TRUE
